### ISSUE TITLE
Uncorrect Typo

### ISSUE THREAD

**Issue by phanvigiaii** [yeungon/In-JavaScript-we-trust#10]
![image](https://user-images.githubusercontent.com/41542555/120280849-6b170400-c2e2-11eb-8fb6-8484b0fa3af2.png)

Dear sir, the question 54 has 1 uncorrect typo is **As getInfo() is an arrow function** -> must be correct with **As content() is an arrow function**
Thanks !

**Comment by yeungon** [comment]
thanks @phanvigiaii :-), I am going to fix it in minutes.
