### ISSUE TITLE
https://github.com/yeungon/In-JavaScript-we-trust

### ISSUE THREAD

**Issue by Anhduc2k** [yeungon/In-JavaScript-we-trust#5]

**Comment by yeungon** [comment]
Hi,

Happy you are here. Please describe any issue you are dealing with then we can fix it together :-)/

**Comment by AdhvaithaNayak** [comment]
I'm completely new to this, i mean open source n stuff, but i want to learn n contribute to open source projects. Please help n guide . i'm still learning JavaScript

**Comment by yeungon** [comment]
@AdhvaithaNayak you can start build some projects with JavaScript bro.
