### ISSUE TITLE
Online H5

### ISSUE THREAD

**Issue by yi-ge** [yeungon/In-JavaScript-we-trust#7]
https://github.com/yi-ge/javascript-exercises

Thanks yeungon.

**Comment by yeungon** [comment]
Thanks @yi-ge for making the online portal for those who want to practise JS :-)

**Comment by CONTIGEN** [comment]
Nice one @yeungon for this JS Exercise.
Really stretches the brain and fun!

**Comment by yeungon** [comment]
Thanks @CONTIGEN, sometimes I myself revisit a question and wonder how can I write such a complicated code :100:
